version: 2
jobs:
  validate_terraform:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1b:2c:f4:63:f3:92:ea:74:5e:6b:cf:16:3f:6f:85:a2"
      - run:
          name: Set up Terraform
          command: terraform init -input=false 
      - run:
          name: Validate Terraform
          command: terraform validate -check-variables=true 
      - run:
          name: Refresh for drifters
          command: terraform refresh -input=false
      - run: 
          name: Plan
          command: terraform plan -input=false -out=tfplan
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_env:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy full environment
          command: terraform apply -input=false tfplan
      - run:
          name: Taint Terraform
          command: terraform taint -module='instances' 'aws_instance.saltmaster'

workflows:
  version: 2
  validate_and_deploy:
    jobs:
      - validate_terraform
      - deploy_env:
          filters:
            branches:
              only: master
          requires:
            - validate_terraform